/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RequestTypeEnum } from './request-type-enum';
import { SpareTimeExecuteTypes } from './spare-time-execute-types';
import { SpareTimeTypes } from './spare-time-types';

/**
 * 
 * @export
 * @interface AddJobInput
 */
export interface AddJobInput {
    /**
     * 任务名称
     * @type {string}
     * @memberof AddJobInput
     */
    jobName?: string | null;
    /**
     * 只执行一次
     * @type {boolean}
     * @memberof AddJobInput
     */
    doOnce?: boolean;
    /**
     * 立即执行（默认等待启动）
     * @type {boolean}
     * @memberof AddJobInput
     */
    startNow?: boolean;
    /**
     * 
     * @type {SpareTimeExecuteTypes}
     * @memberof AddJobInput
     */
    executeType?: SpareTimeExecuteTypes;
    /**
     * 执行间隔时间（单位秒）
     * @type {number}
     * @memberof AddJobInput
     */
    interval?: number;
    /**
     * Cron表达式
     * @type {string}
     * @memberof AddJobInput
     */
    cron?: string | null;
    /**
     * 
     * @type {SpareTimeTypes}
     * @memberof AddJobInput
     */
    timerType?: SpareTimeTypes;
    /**
     * 请求url
     * @type {string}
     * @memberof AddJobInput
     */
    requestUrl?: string | null;
    /**
     * 请求参数（Post，Put请求用）
     * @type {string}
     * @memberof AddJobInput
     */
    requestParameters?: string | null;
    /**
     * Headers(可以包含如：Authorization授权认证)  格式：{\"Authorization\":\"userpassword..\"}
     * @type {string}
     * @memberof AddJobInput
     */
    headers?: string | null;
    /**
     * 
     * @type {RequestTypeEnum}
     * @memberof AddJobInput
     */
    requestType?: RequestTypeEnum;
    /**
     * 备注
     * @type {string}
     * @memberof AddJobInput
     */
    remark?: string | null;
}


