/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddConfigInput
 */
export interface AddConfigInput {
    /**
     * 名称
     * @type {string}
     * @memberof AddConfigInput
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof AddConfigInput
     */
    code: string;
    /**
     * 属性值
     * @type {string}
     * @memberof AddConfigInput
     */
    value?: string | null;
    /**
     * 是否是系统参数（Y-是，N-否）
     * @type {string}
     * @memberof AddConfigInput
     */
    sysFlag?: string | null;
    /**
     * 备注
     * @type {string}
     * @memberof AddConfigInput
     */
    remark?: string | null;
    /**
     * 状态（字典 0正常 1停用 2删除）
     * @type {number}
     * @memberof AddConfigInput
     */
    status?: number;
    /**
     * 常量所属分类的编码，来自于“常量的分类”字典
     * @type {string}
     * @memberof AddConfigInput
     */
    groupCode?: string | null;
}


