/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';
import { EmpOutput2 } from './emp-output2';

/**
 * 
 * @export
 * @interface AddUserInput
 */
export interface AddUserInput {
    /**
     * 账号
     * @type {string}
     * @memberof AddUserInput
     */
    account: string;
    /**
     * 密码
     * @type {string}
     * @memberof AddUserInput
     */
    password: string;
    /**
     * 确认密码
     * @type {string}
     * @memberof AddUserInput
     */
    confirm: string;
    /**
     * 昵称
     * @type {string}
     * @memberof AddUserInput
     */
    nickName?: string | null;
    /**
     * 姓名
     * @type {string}
     * @memberof AddUserInput
     */
    name?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof AddUserInput
     */
    avatar?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof AddUserInput
     */
    birthday?: string | null;
    /**
     * 性别-男_1、女_2
     * @type {number}
     * @memberof AddUserInput
     */
    sex?: number;
    /**
     * 邮箱
     * @type {string}
     * @memberof AddUserInput
     */
    email?: string | null;
    /**
     * 手机
     * @type {string}
     * @memberof AddUserInput
     */
    phone?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof AddUserInput
     */
    tel?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof AddUserInput
     */
    status?: CommonStatus;
    /**
     * 
     * @type {EmpOutput2}
     * @memberof AddUserInput
     */
    sysEmpParam?: EmpOutput2;
}


