/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { QueryTypeEnum } from './query-type-enum';

/**
 * 查询条件
 * @export
 * @interface Condition
 */
export interface Condition {
    /**
     * 字段名
     * @type {string}
     * @memberof Condition
     */
    field?: string | null;
    /**
     * 
     * @type {QueryTypeEnum}
     * @memberof Condition
     */
    op?: QueryTypeEnum;
    /**
     * 字段值
     * @type {any}
     * @memberof Condition
     */
    value?: any | null;
    /**
     * 分组名称
     * @type {string}
     * @memberof Condition
     */
    orGroup?: string | null;
}


