/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 附属机构和职位参数
 * @export
 * @interface EmpExtOrgPosOutput
 */
export interface EmpExtOrgPosOutput {
    /**
     * 附属机构id
     * @type {number}
     * @memberof EmpExtOrgPosOutput
     */
    orgId?: number;
    /**
     * 附属机构编码
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    orgCode?: string | null;
    /**
     * 附属机构名称
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    orgName?: string | null;
    /**
     * 附属职位id
     * @type {number}
     * @memberof EmpExtOrgPosOutput
     */
    posId?: number;
    /**
     * 附属职位编码
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    posCode?: string | null;
    /**
     * 附属职位名称
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    posName?: string | null;
}


