/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmpExtOrgPosOutput } from './emp-ext-org-pos-output';

/**
 * 员工信息参数2
 * @export
 * @interface EmpOutput2
 */
export interface EmpOutput2 {
    /**
     * 员工Id
     * @type {string}
     * @memberof EmpOutput2
     */
    id?: string | null;
    /**
     * 工号
     * @type {string}
     * @memberof EmpOutput2
     */
    jobNum?: string | null;
    /**
     * 机构Id
     * @type {string}
     * @memberof EmpOutput2
     */
    orgId?: string | null;
    /**
     * 机构名称
     * @type {string}
     * @memberof EmpOutput2
     */
    orgName?: string | null;
    /**
     * 附属机构
     * @type {Array<EmpExtOrgPosOutput>}
     * @memberof EmpOutput2
     */
    extIds?: Array<EmpExtOrgPosOutput> | null;
    /**
     * 职位集合
     * @type {Array<number>}
     * @memberof EmpOutput2
     */
    posIdList?: Array<number> | null;
}


