/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GrantRoleDataInput
 */
export interface GrantRoleDataInput {
    /**
     * 角色Id
     * @type {number}
     * @memberof GrantRoleDataInput
     */
    id: number;
    /**
     * 名称
     * @type {string}
     * @memberof GrantRoleDataInput
     */
    name?: string | null;
    /**
     * 编码
     * @type {string}
     * @memberof GrantRoleDataInput
     */
    code?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof GrantRoleDataInput
     */
    sort?: number;
    /**
     * 数据范围类型（字典 1全部数据 2本部门及以下数据 3本部门数据 4仅本人数据 5自定义数据）
     * @type {number}
     * @memberof GrantRoleDataInput
     */
    dataScopeType?: number;
    /**
     * 备注
     * @type {string}
     * @memberof GrantRoleDataInput
     */
    remark?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GrantRoleDataInput
     */
    grantMenuIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GrantRoleDataInput
     */
    grantRoleIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GrantRoleDataInput
     */
    grantOrgIdList?: Array<number> | null;
}


