/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Condition } from './condition';
import { RequestTypeEnum } from './request-type-enum';
import { SpareTimeExecuteTypes } from './spare-time-execute-types';
import { SpareTimeTypes } from './spare-time-types';

/**
 * 任务调度参数
 * @export
 * @interface JobPageInput
 */
export interface JobPageInput {
    /**
     * 搜索值
     * @type {string}
     * @memberof JobPageInput
     */
    searchValue?: string | null;
    /**
     * 当前页码
     * @type {number}
     * @memberof JobPageInput
     */
    pageNo?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof JobPageInput
     */
    pageSize?: number;
    /**
     * 搜索开始时间
     * @type {string}
     * @memberof JobPageInput
     */
    searchBeginTime?: string | null;
    /**
     * 搜索结束时间
     * @type {string}
     * @memberof JobPageInput
     */
    searchEndTime?: string | null;
    /**
     * 排序字段
     * @type {string}
     * @memberof JobPageInput
     */
    sortField?: string | null;
    /**
     * 排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
     * @type {string}
     * @memberof JobPageInput
     */
    sortOrder?: string | null;
    /**
     * 降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
     * @type {string}
     * @memberof JobPageInput
     */
    descStr?: string | null;
    /**
     * 复杂查询条件
     * @type {Array<Condition>}
     * @memberof JobPageInput
     */
    searchParameters?: Array<Condition> | null;
    /**
     * 任务名称
     * @type {string}
     * @memberof JobPageInput
     */
    jobName?: string | null;
    /**
     * 只执行一次
     * @type {boolean}
     * @memberof JobPageInput
     */
    doOnce?: boolean;
    /**
     * 立即执行（默认等待启动）
     * @type {boolean}
     * @memberof JobPageInput
     */
    startNow?: boolean;
    /**
     * 
     * @type {SpareTimeExecuteTypes}
     * @memberof JobPageInput
     */
    executeType?: SpareTimeExecuteTypes;
    /**
     * 执行间隔时间（单位秒）
     * @type {number}
     * @memberof JobPageInput
     */
    interval?: number;
    /**
     * Cron表达式
     * @type {string}
     * @memberof JobPageInput
     */
    cron?: string | null;
    /**
     * 
     * @type {SpareTimeTypes}
     * @memberof JobPageInput
     */
    timerType?: SpareTimeTypes;
    /**
     * 请求url
     * @type {string}
     * @memberof JobPageInput
     */
    requestUrl?: string | null;
    /**
     * 请求参数（Post，Put请求用）
     * @type {string}
     * @memberof JobPageInput
     */
    requestParameters?: string | null;
    /**
     * Headers(可以包含如：Authorization授权认证)  格式：{\"Authorization\":\"userpassword..\"}
     * @type {string}
     * @memberof JobPageInput
     */
    headers?: string | null;
    /**
     * 
     * @type {RequestTypeEnum}
     * @memberof JobPageInput
     */
    requestType?: RequestTypeEnum;
    /**
     * 备注
     * @type {string}
     * @memberof JobPageInput
     */
    remark?: string | null;
}


