/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AntDesignTreeNode } from './ant-design-tree-node';
import { AppOutput } from './app-output';

/**
 * 用户权限输出参数
 * @export
 * @interface LoginAuthOutput
 */
export interface LoginAuthOutput {
    /**
     * 具备应用信息
     * @type {Array<AppOutput>}
     * @memberof LoginAuthOutput
     */
    apps?: Array<AppOutput> | null;
    /**
     * 权限信息
     * @type {Array<string>}
     * @memberof LoginAuthOutput
     */
    permissions?: Array<string> | null;
    /**
     * 登录菜单信息---AntDesign版本菜单
     * @type {Array<AntDesignTreeNode>}
     * @memberof LoginAuthOutput
     */
    menus?: Array<AntDesignTreeNode> | null;
    /**
     * 数据范围（机构）信息
     * @type {Array<number>}
     * @memberof LoginAuthOutput
     */
    dataScopes?: Array<number> | null;
}


