/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AntDesignTreeNode } from './ant-design-tree-node';
import { AppOutput } from './app-output';
import { EmpOutput } from './emp-output';
import { RoleOutput } from './role-output';

/**
 * 用户登录输出参数
 * @export
 * @interface LoginOutput
 */
export interface LoginOutput {
    /**
     * 主键
     * @type {number}
     * @memberof LoginOutput
     */
    id?: number;
    /**
     * 账号
     * @type {string}
     * @memberof LoginOutput
     */
    account?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof LoginOutput
     */
    nickName?: string | null;
    /**
     * 姓名
     * @type {string}
     * @memberof LoginOutput
     */
    name?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof LoginOutput
     */
    avatar?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof LoginOutput
     */
    birthday?: string | null;
    /**
     * 性别(字典 1男 2女)
     * @type {number}
     * @memberof LoginOutput
     */
    sex?: number;
    /**
     * 邮箱
     * @type {string}
     * @memberof LoginOutput
     */
    email?: string | null;
    /**
     * 手机
     * @type {string}
     * @memberof LoginOutput
     */
    phone?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof LoginOutput
     */
    tel?: string | null;
    /**
     * 管理员类型（1超级管理员 2管理员 3普通账号）
     * @type {number}
     * @memberof LoginOutput
     */
    adminType?: number;
    /**
     * 最后登陆IP
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginIp?: string | null;
    /**
     * 最后登陆时间
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginTime?: string | null;
    /**
     * 最后登陆地址
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginAddress?: string | null;
    /**
     * 最后登陆所用浏览器
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginBrowser?: string | null;
    /**
     * 最后登陆所用系统
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginOs?: string | null;
    /**
     * 
     * @type {EmpOutput}
     * @memberof LoginOutput
     */
    loginEmpInfo?: EmpOutput;
    /**
     * 具备应用信息
     * @type {Array<AppOutput>}
     * @memberof LoginOutput
     */
    apps?: Array<AppOutput> | null;
    /**
     * 角色信息
     * @type {Array<RoleOutput>}
     * @memberof LoginOutput
     */
    roles?: Array<RoleOutput> | null;
    /**
     * 权限信息
     * @type {Array<string>}
     * @memberof LoginOutput
     */
    permissions?: Array<string> | null;
    /**
     * 系统所有权限信息
     * @type {Array<string>}
     * @memberof LoginOutput
     */
    allPermissions?: Array<string> | null;
    /**
     * 登录菜单信息---AntDesign版本菜单
     * @type {Array<AntDesignTreeNode>}
     * @memberof LoginOutput
     */
    menus?: Array<AntDesignTreeNode> | null;
    /**
     * 数据范围（机构）信息
     * @type {Array<number>}
     * @memberof LoginOutput
     */
    dataScopes?: Array<number> | null;
}


