/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmpOutput } from './emp-output';
import { RoleOutput } from './role-output';

/**
 * 用户基本信息输出参数
 * @export
 * @interface LoginUserOutput
 */
export interface LoginUserOutput {
    /**
     * 主键
     * @type {number}
     * @memberof LoginUserOutput
     */
    id?: number;
    /**
     * 账号
     * @type {string}
     * @memberof LoginUserOutput
     */
    account?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof LoginUserOutput
     */
    nickName?: string | null;
    /**
     * 姓名
     * @type {string}
     * @memberof LoginUserOutput
     */
    name?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof LoginUserOutput
     */
    avatar?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof LoginUserOutput
     */
    birthday?: string | null;
    /**
     * 性别(字典 1男 2女)
     * @type {number}
     * @memberof LoginUserOutput
     */
    sex?: number;
    /**
     * 邮箱
     * @type {string}
     * @memberof LoginUserOutput
     */
    email?: string | null;
    /**
     * 手机
     * @type {string}
     * @memberof LoginUserOutput
     */
    phone?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof LoginUserOutput
     */
    tel?: string | null;
    /**
     * 管理员类型（0超级管理员 1非管理员）
     * @type {number}
     * @memberof LoginUserOutput
     */
    adminType?: number;
    /**
     * 最后登陆IP
     * @type {string}
     * @memberof LoginUserOutput
     */
    lastLoginIp?: string | null;
    /**
     * 最后登陆时间
     * @type {string}
     * @memberof LoginUserOutput
     */
    lastLoginTime?: string | null;
    /**
     * 最后登陆地址
     * @type {string}
     * @memberof LoginUserOutput
     */
    lastLoginAddress?: string | null;
    /**
     * 最后登陆所用浏览器
     * @type {string}
     * @memberof LoginUserOutput
     */
    lastLoginBrowser?: string | null;
    /**
     * 最后登陆所用系统
     * @type {string}
     * @memberof LoginUserOutput
     */
    lastLoginOs?: string | null;
    /**
     * 
     * @type {EmpOutput}
     * @memberof LoginUserOutput
     */
    loginEmpInfo?: EmpOutput;
    /**
     * 角色信息
     * @type {Array<RoleOutput>}
     * @memberof LoginUserOutput
     */
    roles?: Array<RoleOutput> | null;
}


