/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoticeUserStatus } from './notice-user-status';

/**
 * 
 * @export
 * @interface NoticeUserRead
 */
export interface NoticeUserRead {
    /**
     * 用户Id
     * @type {number}
     * @memberof NoticeUserRead
     */
    userId?: number;
    /**
     * 用户名称
     * @type {string}
     * @memberof NoticeUserRead
     */
    userName?: string | null;
    /**
     * 
     * @type {NoticeUserStatus}
     * @memberof NoticeUserRead
     */
    readStatus?: NoticeUserStatus;
    /**
     * 阅读时间
     * @type {string}
     * @memberof NoticeUserRead
     */
    readTime?: string | null;
}


