/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoticeUserRead } from './notice-user-read';

/**
 * 系统通知公告详情参数
 * @export
 * @interface NoticeDetailOutput
 */
export interface NoticeDetailOutput {
    /**
     * 标题
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    title?: string | null;
    /**
     * 内容
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    content?: string | null;
    /**
     * 类型（字典 1通知 2公告）
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    type?: number;
    /**
     * 发布人Id
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    publicUserId?: number;
    /**
     * 发布人姓名
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    publicUserName?: string | null;
    /**
     * 发布机构Id
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    publicOrgId?: number;
    /**
     * 发布机构名称
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    publicOrgName?: string | null;
    /**
     * 发布时间
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    publicTime?: string | null;
    /**
     * 撤回时间
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    cancelTime?: string | null;
    /**
     * 状态（字典 0草稿 1发布 2撤回 3删除）
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    status?: number;
    /**
     * 通知到的用户Id集合
     * @type {Array<string>}
     * @memberof NoticeDetailOutput
     */
    noticeUserIdList?: Array<string> | null;
    /**
     * 通知到的用户阅读信息集合
     * @type {Array<NoticeUserRead>}
     * @memberof NoticeDetailOutput
     */
    noticeUserReadInfoList?: Array<NoticeUserRead> | null;
}


