/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 查询类型枚举<br />&nbsp;等于 Equals = Equals<br />&nbsp;不等于 NotEquals = NotEquals<br />&nbsp;大于 GreaterThan = GreaterThan<br />&nbsp;大于等于 GreaterThanOrEquals = GreaterThanOrEquals<br />&nbsp;小于 LessThan = LessThan<br />&nbsp;小于等于 LessThanOrEquals = LessThanOrEquals<br />&nbsp;在列表中 StdIn = StdIn<br />&nbsp;不在列表中 StdNotIn = StdNotIn<br />&nbsp;包含 Contains = Contains<br />&nbsp;不包含 NotContains = NotContains<br />&nbsp;头部包含 StartsWith = StartsWith<br />&nbsp;尾部包含 EndsWith = EndsWith<br />
 * @export
 * @enum {string}
 */
export enum QueryTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11
}



