/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoleTypeEnum } from './role-type-enum';

/**
 * 登录用户角色参数
 * @export
 * @interface RoleOutput
 */
export interface RoleOutput {
    /**
     * 
     * @type {RoleTypeEnum}
     * @memberof RoleOutput
     */
    roleType?: RoleTypeEnum;
    /**
     * Id
     * @type {number}
     * @memberof RoleOutput
     */
    id?: number;
    /**
     * 编码
     * @type {string}
     * @memberof RoleOutput
     */
    code?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof RoleOutput
     */
    name?: string | null;
}


