/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';

/**
 * 系统应用表
 * @export
 * @interface SysApp
 */
export interface SysApp {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysApp
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysApp
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysApp
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysApp
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysApp
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysApp
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysApp
     */
    updatedUserName?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysApp
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof SysApp
     */
    code: string;
    /**
     * 是否默认激活（Y-是，N-否）,只能有一个系统默认激活  用户登录后默认展示此系统菜单
     * @type {string}
     * @memberof SysApp
     */
    active?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysApp
     */
    status?: CommonStatus;
    /**
     * 排序
     * @type {number}
     * @memberof SysApp
     */
    sort?: number;
}


