/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 文件信息表
 * @export
 * @interface SysFile
 */
export interface SysFile {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysFile
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysFile
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysFile
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysFile
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysFile
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysFile
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysFile
     */
    updatedUserName?: string | null;
    /**
     * 文件存储位置（1:阿里云，2:腾讯云，3:minio，4:本地）
     * @type {number}
     * @memberof SysFile
     */
    fileLocation?: number;
    /**
     * 文件仓库
     * @type {string}
     * @memberof SysFile
     */
    fileBucket?: string | null;
    /**
     * 文件名称（上传时候的文件名）
     * @type {string}
     * @memberof SysFile
     */
    fileOriginName?: string | null;
    /**
     * 文件后缀
     * @type {string}
     * @memberof SysFile
     */
    fileSuffix?: string | null;
    /**
     * 文件大小kb
     * @type {string}
     * @memberof SysFile
     */
    fileSizeKb?: string | null;
    /**
     * 文件大小信息，计算后的
     * @type {string}
     * @memberof SysFile
     */
    fileSizeInfo?: string | null;
    /**
     * 存储到bucket的名称（文件唯一标识id）
     * @type {string}
     * @memberof SysFile
     */
    fileObjectName?: string | null;
    /**
     * 存储路径
     * @type {string}
     * @memberof SysFile
     */
    filePath?: string | null;
}


