/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';
import { MenuOpenType } from './menu-open-type';
import { MenuType } from './menu-type';
import { MenuWeight } from './menu-weight';
import { SysRole } from './sys-role';
import { SysRoleMenu } from './sys-role-menu';

/**
 * 菜单表
 * @export
 * @interface SysMenu
 */
export interface SysMenu {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysMenu
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysMenu
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysMenu
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysMenu
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysMenu
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysMenu
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysMenu
     */
    updatedUserName?: string | null;
    /**
     * 父Id
     * @type {number}
     * @memberof SysMenu
     */
    pid?: number;
    /**
     * 父Ids
     * @type {string}
     * @memberof SysMenu
     */
    pids?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysMenu
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof SysMenu
     */
    code: string;
    /**
     * 
     * @type {MenuType}
     * @memberof SysMenu
     */
    type?: MenuType;
    /**
     * 图标
     * @type {string}
     * @memberof SysMenu
     */
    icon?: string | null;
    /**
     * 路由地址
     * @type {string}
     * @memberof SysMenu
     */
    router?: string | null;
    /**
     * 组件地址
     * @type {string}
     * @memberof SysMenu
     */
    component?: string | null;
    /**
     * 忽略缓存
     * @type {boolean}
     * @memberof SysMenu
     */
    ignoreKeepAlive?: boolean;
    /**
     * 权限标识
     * @type {string}
     * @memberof SysMenu
     */
    permission?: string | null;
    /**
     * 应用分类（应用编码）
     * @type {string}
     * @memberof SysMenu
     */
    application?: string | null;
    /**
     * 
     * @type {MenuOpenType}
     * @memberof SysMenu
     */
    openType?: MenuOpenType;
    /**
     * 是否可见（Y-是，N-否）
     * @type {string}
     * @memberof SysMenu
     */
    visible?: string | null;
    /**
     * 内链地址
     * @type {string}
     * @memberof SysMenu
     */
    link?: string | null;
    /**
     * 重定向地址
     * @type {string}
     * @memberof SysMenu
     */
    redirect?: string | null;
    /**
     * 
     * @type {MenuWeight}
     * @memberof SysMenu
     */
    weight?: MenuWeight;
    /**
     * 排序
     * @type {number}
     * @memberof SysMenu
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof SysMenu
     */
    remark?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysMenu
     */
    status?: CommonStatus;
    /**
     * 多对多（角色）
     * @type {Array<SysRole>}
     * @memberof SysMenu
     */
    sysRoles?: Array<SysRole> | null;
    /**
     * 多对多中间表（用户角色）
     * @type {Array<SysRoleMenu>}
     * @memberof SysMenu
     */
    sysRoleMenus?: Array<SysRoleMenu> | null;
}


