/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SysRole } from './sys-role';
import { SysUser } from './sys-user';

/**
 * 用户角色表
 * @export
 * @interface SysUserRole
 */
export interface SysUserRole {
    /**
     * 用户Id
     * @type {number}
     * @memberof SysUserRole
     */
    sysUserId?: number;
    /**
     * 
     * @type {SysUser}
     * @memberof SysUserRole
     */
    sysUser?: SysUser;
    /**
     * 系统角色Id
     * @type {number}
     * @memberof SysUserRole
     */
    sysRoleId?: number;
    /**
     * 
     * @type {SysRole}
     * @memberof SysUserRole
     */
    sysRole?: SysRole;
}


