/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AdminType } from './admin-type';
import { CommonStatus } from './common-status';
import { Gender } from './gender';
import { SysOrg } from './sys-org';
import { SysRole } from './sys-role';
import { SysUserDataScope } from './sys-user-data-scope';
import { SysUserRole } from './sys-user-role';

/**
 * 用户表
 * @export
 * @interface SysUser
 */
export interface SysUser {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysUser
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysUser
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysUser
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysUser
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysUser
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysUser
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysUser
     */
    updatedUserName?: string | null;
    /**
     * 租户id
     * @type {number}
     * @memberof SysUser
     */
    tenantId?: number | null;
    /**
     * 账号
     * @type {string}
     * @memberof SysUser
     */
    account: string;
    /**
     * 密码（默认MD5加密）
     * @type {string}
     * @memberof SysUser
     */
    password: string;
    /**
     * 昵称
     * @type {string}
     * @memberof SysUser
     */
    nickName?: string | null;
    /**
     * 姓名
     * @type {string}
     * @memberof SysUser
     */
    name?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof SysUser
     */
    avatar?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof SysUser
     */
    birthday?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof SysUser
     */
    sex?: Gender;
    /**
     * 邮箱
     * @type {string}
     * @memberof SysUser
     */
    email?: string | null;
    /**
     * 手机
     * @type {string}
     * @memberof SysUser
     */
    phone?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof SysUser
     */
    tel?: string | null;
    /**
     * 最后登录IP
     * @type {string}
     * @memberof SysUser
     */
    lastLoginIp?: string | null;
    /**
     * 最后登录时间
     * @type {string}
     * @memberof SysUser
     */
    lastLoginTime?: string | null;
    /**
     * 
     * @type {AdminType}
     * @memberof SysUser
     */
    adminType?: AdminType;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysUser
     */
    status?: CommonStatus;
    /**
     * 多对多（角色）
     * @type {Array<SysRole>}
     * @memberof SysUser
     */
    sysRoles?: Array<SysRole> | null;
    /**
     * 多对多中间表（用户-角色）
     * @type {Array<SysUserRole>}
     * @memberof SysUser
     */
    sysUserRoles?: Array<SysUserRole> | null;
    /**
     * 多对多（机构）
     * @type {Array<SysOrg>}
     * @memberof SysUser
     */
    sysOrgs?: Array<SysOrg> | null;
    /**
     * 多对多中间表（用户-机构 数据范围）
     * @type {Array<SysUserDataScope>}
     * @memberof SysUser
     */
    sysUserDataScopes?: Array<SysUserDataScope> | null;
}


