/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 数据库表列表参数
 * @export
 * @interface TableOutput
 */
export interface TableOutput {
    /**
     * 表名（字母形式的）
     * @type {string}
     * @memberof TableOutput
     */
    tableName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof TableOutput
     */
    createTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof TableOutput
     */
    updateTime?: string | null;
    /**
     * 表名称描述（注释）（功能名）
     * @type {string}
     * @memberof TableOutput
     */
    tableComment?: string | null;
}


