/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmpOutput2 } from './emp-output2';

/**
 * 更新用户授权数据角色和数据范围
 * @export
 * @interface UpdateUserRoleDataInput
 */
export interface UpdateUserRoleDataInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof UpdateUserRoleDataInput
     */
    id: number;
    /**
     * 
     * @type {EmpOutput2}
     * @memberof UpdateUserRoleDataInput
     */
    sysEmpParam?: EmpOutput2;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateUserRoleDataInput
     */
    grantMenuIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateUserRoleDataInput
     */
    grantRoleIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateUserRoleDataInput
     */
    grantOrgIdList?: Array<number> | null;
}


