/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';

/**
 * 
 * @export
 * @interface UpdateDictTypeInput
 */
export interface UpdateDictTypeInput {
    /**
     * Id
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    id: number;
    /**
     * 名称
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    code: string;
    /**
     * 排序
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    remark?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof UpdateDictTypeInput
     */
    status?: CommonStatus;
}


