/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoticeStatus } from './notice-status';

/**
 * 
 * @export
 * @interface UpdateNoticeInput
 */
export interface UpdateNoticeInput {
    /**
     * Id
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    id: number;
    /**
     * 标题
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    title: string;
    /**
     * 内容
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    content: string;
    /**
     * 类型（字典 1通知 2公告）
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    type: number;
    /**
     * 
     * @type {NoticeStatus}
     * @memberof UpdateNoticeInput
     */
    status: NoticeStatus;
    /**
     * 通知到的人
     * @type {Array<number>}
     * @memberof UpdateNoticeInput
     */
    noticeUserIdList: Array<number>;
}


