/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 更新用户基本信息
 * @export
 * @interface UpdateUserBaseInfoInput
 */
export interface UpdateUserBaseInfoInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof UpdateUserBaseInfoInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserBaseInfoInput
     */
    nickName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserBaseInfoInput
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserBaseInfoInput
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserBaseInfoInput
     */
    sex: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserBaseInfoInput
     */
    birthday: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserBaseInfoInput
     */
    tel?: string | null;
}


