/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';
import { Condition } from './condition';
import { EmpOutput2 } from './emp-output2';

/**
 * 用户参数
 * @export
 * @interface UserPageInput
 */
export interface UserPageInput {
    /**
     * 搜索值
     * @type {string}
     * @memberof UserPageInput
     */
    searchValue?: string | null;
    /**
     * 当前页码
     * @type {number}
     * @memberof UserPageInput
     */
    pageNo?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof UserPageInput
     */
    pageSize?: number;
    /**
     * 搜索开始时间
     * @type {string}
     * @memberof UserPageInput
     */
    searchBeginTime?: string | null;
    /**
     * 搜索结束时间
     * @type {string}
     * @memberof UserPageInput
     */
    searchEndTime?: string | null;
    /**
     * 排序字段
     * @type {string}
     * @memberof UserPageInput
     */
    sortField?: string | null;
    /**
     * 排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
     * @type {string}
     * @memberof UserPageInput
     */
    sortOrder?: string | null;
    /**
     * 降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
     * @type {string}
     * @memberof UserPageInput
     */
    descStr?: string | null;
    /**
     * 复杂查询条件
     * @type {Array<Condition>}
     * @memberof UserPageInput
     */
    searchParameters?: Array<Condition> | null;
    /**
     * 账号
     * @type {string}
     * @memberof UserPageInput
     */
    account?: string | null;
    /**
     * 密码
     * @type {string}
     * @memberof UserPageInput
     */
    password?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof UserPageInput
     */
    nickName?: string | null;
    /**
     * 姓名
     * @type {string}
     * @memberof UserPageInput
     */
    name?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof UserPageInput
     */
    avatar?: string | null;
    /**
     * 生日
     * @type {string}
     * @memberof UserPageInput
     */
    birthday?: string | null;
    /**
     * 性别-男_1、女_2
     * @type {number}
     * @memberof UserPageInput
     */
    sex?: number;
    /**
     * 邮箱
     * @type {string}
     * @memberof UserPageInput
     */
    email?: string | null;
    /**
     * 手机
     * @type {string}
     * @memberof UserPageInput
     */
    phone?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof UserPageInput
     */
    tel?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof UserPageInput
     */
    status?: CommonStatus;
    /**
     * 
     * @type {EmpOutput2}
     * @memberof UserPageInput
     */
    sysEmpParam?: EmpOutput2;
    /**
     * 
     * @type {CommonStatus}
     * @memberof UserPageInput
     */
    searchStatus?: CommonStatus;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserPageInput
     */
    grantMenuIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserPageInput
     */
    grantRoleIdList?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserPageInput
     */
    grantOrgIdList?: Array<number> | null;
}


