/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Meta } from './meta';

/**
 * 登录菜单-AntDesign菜单类型
 * @export
 * @interface AntDesignTreeNode
 */
export interface AntDesignTreeNode {
    /**
     * id
     * @type {number}
     * @memberof AntDesignTreeNode
     */
    id?: number | null;
    /**
     * 父id
     * @type {number}
     * @memberof AntDesignTreeNode
     */
    pid?: number | null;
    /**
     * 路由名称, 必须设置,且不能重名
     * @type {string}
     * @memberof AntDesignTreeNode
     */
    name?: string | null;
    /**
     * 组件
     * @type {string}
     * @memberof AntDesignTreeNode
     */
    component?: string | null;
    /**
     * 重定向地址, 访问这个路由时, 自定进行重定向
     * @type {string}
     * @memberof AntDesignTreeNode
     */
    redirect?: string | null;
    /**
     * 
     * @type {Meta}
     * @memberof AntDesignTreeNode
     */
    meta?: Meta;
    /**
     * 路径
     * @type {string}
     * @memberof AntDesignTreeNode
     */
    path?: string | null;
    /**
     * 控制路由和子路由是否显示在 sidebar
     * @type {boolean}
     * @memberof AntDesignTreeNode
     */
    hidden?: boolean;
}


