/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 字典类型与字典值构造的树
 * @export
 * @interface DictTreeOutput
 */
export interface DictTreeOutput {
    /**
     * Id
     * @type {number}
     * @memberof DictTreeOutput
     */
    id?: number;
    /**
     * 父Id
     * @type {number}
     * @memberof DictTreeOutput
     */
    pid?: number;
    /**
     * 编码-对应字典值的编码
     * @type {string}
     * @memberof DictTreeOutput
     */
    code?: string | null;
    /**
     * 名称-对应字典值的value
     * @type {string}
     * @memberof DictTreeOutput
     */
    name?: string | null;
    /**
     * 子节点集合
     * @type {Array<DictTreeOutput>}
     * @memberof DictTreeOutput
     */
    children?: Array<DictTreeOutput> | null;
}


