/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmpExtOrgPosOutput } from './emp-ext-org-pos-output';
import { EmpPosOutput } from './emp-pos-output';

/**
 * 员工信息参数
 * @export
 * @interface EmpOutput
 */
export interface EmpOutput {
    /**
     * 工号
     * @type {string}
     * @memberof EmpOutput
     */
    jobNum?: string | null;
    /**
     * 机构id
     * @type {string}
     * @memberof EmpOutput
     */
    orgId?: string | null;
    /**
     * 机构名称
     * @type {string}
     * @memberof EmpOutput
     */
    orgName?: string | null;
    /**
     * 机构与职位信息
     * @type {Array<EmpExtOrgPosOutput>}
     * @memberof EmpOutput
     */
    extOrgPos?: Array<EmpExtOrgPosOutput> | null;
    /**
     * 职位信息
     * @type {Array<EmpPosOutput>}
     * @memberof EmpOutput
     */
    positions?: Array<EmpPosOutput> | null;
}


