/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 机构类型<br />&nbsp;品牌 BRAND = BRAND<br />&nbsp;总店(加盟/直营) HEAD = HEAD<br />&nbsp;直营店 DIRECT = DIRECT<br />&nbsp;加盟店 FRANCHISED = FRANCHISED<br />
 * @export
 * @enum {string}
 */
export enum OrgTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}



