/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SysEmp } from './sys-emp';
import { SysPos } from './sys-pos';

/**
 * 员工职位表
 * @export
 * @interface SysEmpPos
 */
export interface SysEmpPos {
    /**
     * 员工Id
     * @type {number}
     * @memberof SysEmpPos
     */
    sysEmpId?: number;
    /**
     * 
     * @type {SysEmp}
     * @memberof SysEmpPos
     */
    sysEmp?: SysEmp;
    /**
     * 职位Id
     * @type {number}
     * @memberof SysEmpPos
     */
    sysPosId?: number;
    /**
     * 
     * @type {SysPos}
     * @memberof SysEmpPos
     */
    sysPos?: SysPos;
}


