/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 代码生成表
 * @export
 * @interface SysCodeGen
 */
export interface SysCodeGen {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysCodeGen
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysCodeGen
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysCodeGen
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysCodeGen
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysCodeGen
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysCodeGen
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysCodeGen
     */
    updatedUserName?: string | null;
    /**
     * 作者姓名
     * @type {string}
     * @memberof SysCodeGen
     */
    authorName?: string | null;
    /**
     * 是否移除表前缀
     * @type {string}
     * @memberof SysCodeGen
     */
    tablePrefix?: string | null;
    /**
     * 生成方式
     * @type {string}
     * @memberof SysCodeGen
     */
    generateType?: string | null;
    /**
     * 数据库表名
     * @type {string}
     * @memberof SysCodeGen
     */
    tableName?: string | null;
    /**
     * 命名空间
     * @type {string}
     * @memberof SysCodeGen
     */
    nameSpace?: string | null;
    /**
     * 程序集
     * @type {string}
     * @memberof SysCodeGen
     */
    proName?: string | null;
    /**
     * 业务名
     * @type {string}
     * @memberof SysCodeGen
     */
    busName?: string | null;
    /**
     * 菜单应用分类（应用编码）
     * @type {string}
     * @memberof SysCodeGen
     */
    menuApplication?: string | null;
    /**
     * 菜单编码
     * @type {number}
     * @memberof SysCodeGen
     */
    menuPid?: number;
}


