/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';
import { DataScopeType } from './data-scope-type';
import { RoleTypeEnum } from './role-type-enum';
import { SysMenu } from './sys-menu';
import { SysOrg } from './sys-org';
import { SysRoleDataScope } from './sys-role-data-scope';
import { SysRoleMenu } from './sys-role-menu';
import { SysUser } from './sys-user';
import { SysUserRole } from './sys-user-role';

/**
 * 角色表
 * @export
 * @interface SysRole
 */
export interface SysRole {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysRole
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysRole
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysRole
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysRole
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysRole
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysRole
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysRole
     */
    updatedUserName?: string | null;
    /**
     * 租户id
     * @type {number}
     * @memberof SysRole
     */
    tenantId?: number | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysRole
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof SysRole
     */
    code: string;
    /**
     * 排序
     * @type {number}
     * @memberof SysRole
     */
    sort?: number;
    /**
     * 
     * @type {DataScopeType}
     * @memberof SysRole
     */
    dataScopeType?: DataScopeType;
    /**
     * 备注
     * @type {string}
     * @memberof SysRole
     */
    remark?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysRole
     */
    status?: CommonStatus;
    /**
     * 
     * @type {RoleTypeEnum}
     * @memberof SysRole
     */
    roleType?: RoleTypeEnum;
    /**
     * 多对多（用户）
     * @type {Array<SysUser>}
     * @memberof SysRole
     */
    sysUsers?: Array<SysUser> | null;
    /**
     * 多对多中间表（用户角色）
     * @type {Array<SysUserRole>}
     * @memberof SysRole
     */
    sysUserRoles?: Array<SysUserRole> | null;
    /**
     * 多对多（机构）
     * @type {Array<SysOrg>}
     * @memberof SysRole
     */
    sysOrgs?: Array<SysOrg> | null;
    /**
     * 多对多中间表（角色-机构 数据范围）
     * @type {Array<SysRoleDataScope>}
     * @memberof SysRole
     */
    sysRoleDataScopes?: Array<SysRoleDataScope> | null;
    /**
     * 多对多（菜单）
     * @type {Array<SysMenu>}
     * @memberof SysRole
     */
    sysMenus?: Array<SysMenu> | null;
    /**
     * 多对多中间表（角色-菜单）
     * @type {Array<SysRoleMenu>}
     * @memberof SysRole
     */
    sysRoleMenus?: Array<SysRoleMenu> | null;
}


