/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';

/**
 * 参数配置表
 * @export
 * @interface SysConfig
 */
export interface SysConfig {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysConfig
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysConfig
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysConfig
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysConfig
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysConfig
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysConfig
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysConfig
     */
    updatedUserName?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysConfig
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof SysConfig
     */
    code: string;
    /**
     * 属性值
     * @type {string}
     * @memberof SysConfig
     */
    value?: string | null;
    /**
     * 是否是系统参数（Y-是，N-否）
     * @type {string}
     * @memberof SysConfig
     */
    sysFlag?: string | null;
    /**
     * 备注
     * @type {string}
     * @memberof SysConfig
     */
    remark?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysConfig
     */
    status?: CommonStatus;
    /**
     * 常量所属分类的编码，来自于“常量的分类”字典
     * @type {string}
     * @memberof SysConfig
     */
    groupCode?: string | null;
}


