/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SysMenu } from './sys-menu';
import { SysRole } from './sys-role';

/**
 * 角色菜单表
 * @export
 * @interface SysRoleMenu
 */
export interface SysRoleMenu {
    /**
     * 角色Id
     * @type {number}
     * @memberof SysRoleMenu
     */
    sysRoleId?: number;
    /**
     * 
     * @type {SysRole}
     * @memberof SysRoleMenu
     */
    sysRole?: SysRole;
    /**
     * 菜单Id
     * @type {number}
     * @memberof SysRoleMenu
     */
    sysMenuId?: number;
    /**
     * 
     * @type {SysMenu}
     * @memberof SysRoleMenu
     */
    sysMenu?: SysMenu;
}


