/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 租户表
 * @export
 * @interface SysTenant
 */
export interface SysTenant {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysTenant
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysTenant
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysTenant
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysTenant
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysTenant
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysTenant
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysTenant
     */
    updatedUserName?: string | null;
    /**
     * 公司名称
     * @type {string}
     * @memberof SysTenant
     */
    name: string;
    /**
     * 管理员名称
     * @type {string}
     * @memberof SysTenant
     */
    adminName: string;
    /**
     * 主机
     * @type {string}
     * @memberof SysTenant
     */
    host?: string | null;
    /**
     * 电子邮箱
     * @type {string}
     * @memberof SysTenant
     */
    email?: string | null;
    /**
     * 电话
     * @type {string}
     * @memberof SysTenant
     */
    phone?: string | null;
    /**
     * 数据库连接
     * @type {string}
     * @memberof SysTenant
     */
    connection?: string | null;
    /**
     * 架构
     * @type {string}
     * @memberof SysTenant
     */
    schema?: string | null;
    /**
     * 备注
     * @type {string}
     * @memberof SysTenant
     */
    remark?: string | null;
}


