/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 代码生成字段配置表
 * @export
 * @interface SysCodeGenConfig
 */
export interface SysCodeGenConfig {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    id?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    createdTime?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    updatedTime?: string | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    createdUserId?: number | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    createdUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    updatedUserId?: number | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    updatedUserName?: string | null;
    /**
     * 代码生成主表ID
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    codeGenId?: number;
    /**
     * 数据库字段名
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnName: string;
    /**
     * 字段描述
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnComment?: string | null;
    /**
     * .NET数据类型
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    netType?: string | null;
    /**
     * 作用类型（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    effectType?: string | null;
    /**
     * 外键实体名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkEntityName?: string | null;
    /**
     * 外键显示字段
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkColumnName?: string | null;
    /**
     * 外键显示字段.NET类型
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkColumnNetType?: string | null;
    /**
     * 字典code
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dictTypeCode?: string | null;
    /**
     * 列表是否缩进（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRetract?: string | null;
    /**
     * 是否必填（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRequired?: string | null;
    /**
     * 是否是查询条件
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    queryWhether?: string | null;
    /**
     * 查询方式
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    queryType?: string | null;
    /**
     * 列表显示
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherTable?: string | null;
    /**
     * 列表是否排序
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherOrderBy?: string | null;
    /**
     * 增改
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherAddUpdate?: string | null;
    /**
     * 主键
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnKey?: string | null;
    /**
     * 数据库中类型（物理类型）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dataType?: string | null;
    /**
     * 是否通用字段
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherCommon?: string | null;
}


