/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SysOrg } from './sys-org';
import { SysUser } from './sys-user';

/**
 * 用户数据范围表
 * @export
 * @interface SysUserDataScope
 */
export interface SysUserDataScope {
    /**
     * 用户Id
     * @type {number}
     * @memberof SysUserDataScope
     */
    sysUserId?: number;
    /**
     * 
     * @type {SysUser}
     * @memberof SysUserDataScope
     */
    sysUser?: SysUser;
    /**
     * 机构Id
     * @type {number}
     * @memberof SysUserDataScope
     */
    sysOrgId?: number;
    /**
     * 
     * @type {SysOrg}
     * @memberof SysUserDataScope
     */
    sysOrg?: SysOrg;
}


