/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { defHttp } from '/@/utils/http/axios';
import { RequestOptions, UploadFileParams } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
  AppPageInput,
  AddAppInput,
  BaseId,
  ChangeUserAppStatusInput,
  Condition,
  SetDefaultAppInput,
  UpdateAppInput,
  XnRestfulResultOfObject,
  XnRestfulResultOfSysApp,
} from '../models';

/**
 * @summary 增加系统应用
 * @param {AddAppInput}[addAppInput]
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppAddPost(addAppInput?: AddAppInput, options?: RequestOptions) {
  const params = { ...addAppInput };
  return defHttp.request<void>(
    {
      url: '/sysApp/add',
      method: 'POST',
      headers: { 'Content-Type': 'application/json-patch+json' },
      params,
    },
    options
  );
}

/**
 * @summary 修改用户状态
 * @param {ChangeUserAppStatusInput}[changeUserAppStatusInput]
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppChangeStatusPost(
  changeUserAppStatusInput?: ChangeUserAppStatusInput,
  options?: RequestOptions
) {
  const params = { ...changeUserAppStatusInput };
  return defHttp.request<void>(
    {
      url: '/sysApp/changeStatus',
      method: 'POST',
      headers: { 'Content-Type': 'application/json-patch+json' },
      params,
    },
    options
  );
}

/**
 * @summary 删除系统应用
 * @param {BaseId}[baseId]
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppDeletePost(baseId?: BaseId, options?: RequestOptions) {
  const params = { ...baseId };
  return defHttp.request<void>(
    {
      url: '/sysApp/delete',
      method: 'POST',
      headers: { 'Content-Type': 'application/json-patch+json' },
      params,
    },
    options
  );
}

/**
 * @summary 获取系统应用
 * @param {number}id 主键Id
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppDetailGet(id: number, options?: RequestOptions) {
  // verify required parameter 'id' is not null or undefined
  assertParamExists('sysAppDetailGet', 'id', id);
  const params = {} as any;
  if (id !== undefined) {
    params['Id'] = id;
  }
  return defHttp.request<XnRestfulResultOfSysApp>(
    {
      url: '/sysApp/detail',
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      params,
    },
    options
  );
}

/**
 * @summary 更新系统应用
 * @param {UpdateAppInput}[updateAppInput]
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppEditPost(updateAppInput?: UpdateAppInput, options?: RequestOptions) {
  const params = { ...updateAppInput };
  return defHttp.request<void>(
    {
      url: '/sysApp/edit',
      method: 'POST',
      headers: { 'Content-Type': 'application/json-patch+json' },
      params,
    },
    options
  );
}

/**
 * @summary 获取系统应用列表
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppListGet(options?: RequestOptions) {
  return defHttp.request<XnRestfulResultOfObject>(
    {
      url: '/sysApp/list',
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    },
    options
  );
}

/**
 * @summary 分页查询系统应用
 * @param {string}[name] 名称
 * @param {string}[code] 编码
 * @param {string}[searchValue] 搜索值
 * @param {number}[pageNo] 当前页码
 * @param {number}[pageSize] 页码容量
 * @param {string}[searchBeginTime] 搜索开始时间
 * @param {string}[searchEndTime] 搜索结束时间
 * @param {string}[sortField] 排序字段
 * @param {string}[sortOrder] 排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
 * @param {string}[descStr] 降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
 * @param {Array<Condition>}[searchParameters] 复杂查询条件
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppPageGet(addPageInput?: AppPageInput, options?: RequestOptions) {
  const params = { ...addPageInput };
  return defHttp.request<XnRestfulResultOfObject>(
    {
      url: '/sysApp/page',
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      params,
    },
    options
  );
}

/**
 * @summary 设为默认应用
 * @param {SetDefaultAppInput}[setDefaultAppInput]
 * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
 */
export function sysAppSetAsDefaultPost(
  setDefaultAppInput?: SetDefaultAppInput,
  options?: RequestOptions
) {
  const params = { ...setDefaultAppInput };
  return defHttp.request<void>(
    {
      url: '/sysApp/setAsDefault',
      method: 'POST',
      headers: { 'Content-Type': 'application/json-patch+json' },
      params,
    },
    options
  );
}
