/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddAppInput,
   BaseId,
   ChangeUserAppStatusInput,
   Condition,
   SetDefaultAppInput,
   UpdateAppInput,
   XnRestfulResultOfObject,
   XnRestfulResultOfSysApp,
   } from '../models';

         /**
         * @summary增加系统应用
         * @param {AddAppInput}[addAppInput]
         */
         export function sysAppAddPost(addAppInput?: AddAppInput, mode: ErrorMessageMode = 'message') {
            const params = {  addAppInput  }
            return defHttp.request<void>(
              {
                url: '/sysApp/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary修改用户状态
         * @param {ChangeUserAppStatusInput}[changeUserAppStatusInput]
         */
         export function sysAppChangeStatusPost(changeUserAppStatusInput?: ChangeUserAppStatusInput, mode: ErrorMessageMode = 'message') {
            const params = {  changeUserAppStatusInput  }
            return defHttp.request<void>(
              {
                url: '/sysApp/changeStatus',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除系统应用
         * @param {BaseId}[baseId]
         */
         export function sysAppDeletePost(baseId?: BaseId, mode: ErrorMessageMode = 'message') {
            const params = {  baseId  }
            return defHttp.request<void>(
              {
                url: '/sysApp/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统应用
         * @param {number}id主键Id
         */
         export function sysAppDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysAppDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfSysApp>(
              {
                url: '/sysApp/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新系统应用
         * @param {UpdateAppInput}[updateAppInput]
         */
         export function sysAppEditPost(updateAppInput?: UpdateAppInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateAppInput  }
            return defHttp.request<void>(
              {
                url: '/sysApp/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统应用列表
         */
         export function sysAppListGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysApp/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页查询系统应用
         * @param {string}[name]名称
         * @param {string}[code]编码
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function sysAppPageGet(name?: string, code?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysApp/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary设为默认应用
         * @param {SetDefaultAppInput}[setDefaultAppInput]
         */
         export function sysAppSetAsDefaultPost(setDefaultAppInput?: SetDefaultAppInput, mode: ErrorMessageMode = 'message') {
            const params = {  setDefaultAppInput  }
            return defHttp.request<void>(
              {
                url: '/sysApp/setAsDefault',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
