/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddCodeGenInput,
   Condition,
   DeleteCodeGenInput,
   SysCodeGen,
   UpdateCodeGenInput,
   XnRestfulResultOfListOfTableColumnOuput,
   XnRestfulResultOfListOfTableOutput,
   XnRestfulResultOfObject,
   XnRestfulResultOfSysCodeGen,
   } from '../models';

         /**
         * @summary增加
         * @param {AddCodeGenInput}[addCodeGenInput]
         */
         export function codeGenerateAddPost(addCodeGenInput?: AddCodeGenInput, mode: ErrorMessageMode = 'message') {
            const params = {  addCodeGenInput  }
            return defHttp.request<void>(
              {
                url: '/codeGenerate/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary根据表名获取列
         * @param {string}tableName
         */
         export function codeGenerateColumnListTableNameGet(tableName: string, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'tableName' is not null or undefined
            assertParamExists('codeGenerateColumnListTableNameGet', 'tableName', tableName)
            const params = {  tableName  }
            return defHttp.request<XnRestfulResultOfListOfTableColumnOuput>(
              {
                url: '/codeGenerate/ColumnList/{tableName}',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除
         * @param {Array<DeleteCodeGenInput>}[deleteCodeGenInput]
         */
         export function codeGenerateDeletePost(deleteCodeGenInput?: Array<DeleteCodeGenInput>, mode: ErrorMessageMode = 'message') {
            const params = {  deleteCodeGenInput  }
            return defHttp.request<void>(
              {
                url: '/codeGenerate/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary详情
         * @param {number}id主键Id
         */
         export function codeGenerateDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('codeGenerateDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfSysCodeGen>(
              {
                url: '/codeGenerate/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新
         * @param {UpdateCodeGenInput}[updateCodeGenInput]
         */
         export function codeGenerateEditPost(updateCodeGenInput?: UpdateCodeGenInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateCodeGenInput  }
            return defHttp.request<void>(
              {
                url: '/codeGenerate/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取数据库表(实体)集合
         */
         export function codeGenerateInformationListGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfListOfTableOutput>(
              {
                url: '/codeGenerate/InformationList',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页查询
         * @param {string}[tableName]数据库表名
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function codeGeneratePageGet(tableName?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (tableName !== undefined) {
                params['TableName'] = tableName;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/codeGenerate/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary代码生成_本地项目
         * @param {SysCodeGen}[sysCodeGen]
         */
         export function codeGenerateRunLocalPost(sysCodeGen?: SysCodeGen, mode: ErrorMessageMode = 'message') {
            const params = {  sysCodeGen  }
            return defHttp.request<void>(
              {
                url: '/codeGenerate/runLocal',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
