/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddConfigInput,
   Condition,
   DeleteConfigInput,
   UpdateConfigInput,
   XnRestfulResultOfBoolean,
   XnRestfulResultOfObject,
   XnRestfulResultOfSysConfig,
   } from '../models';

         /**
         * @summary获取验证码开关标识
         */
         export function apiConfigCaptchaOpenFlagGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfBoolean>(
              {
                url: '/api/config/captcha-open-flag',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新配置缓存
         * @param {string}code
         * @param {any}[body]
         */
         export function apiConfigConfigCacheCodePut(code: string, body?: any, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('apiConfigConfigCacheCodePut', 'code', code)
            const params = {  code  }
            return defHttp.request<void>(
              {
                url: '/api/config/config-cache/{code}',
                method: 'PUT',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary增加系统参数配置
         * @param {AddConfigInput}[addConfigInput]
         */
         export function sysConfigAddPost(addConfigInput?: AddConfigInput, mode: ErrorMessageMode = 'message') {
            const params = {  addConfigInput  }
            return defHttp.request<void>(
              {
                url: '/sysConfig/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除系统参数配置
         * @param {DeleteConfigInput}[deleteConfigInput]
         */
         export function sysConfigDeletePost(deleteConfigInput?: DeleteConfigInput, mode: ErrorMessageMode = 'message') {
            const params = {  deleteConfigInput  }
            return defHttp.request<void>(
              {
                url: '/sysConfig/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统参数配置
         * @param {number}id主键Id
         */
         export function sysConfigDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysConfigDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfSysConfig>(
              {
                url: '/sysConfig/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新系统参数配置
         * @param {UpdateConfigInput}[updateConfigInput]
         */
         export function sysConfigEditPost(updateConfigInput?: UpdateConfigInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateConfigInput  }
            return defHttp.request<void>(
              {
                url: '/sysConfig/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统参数配置列表
         */
         export function sysConfigListGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysConfig/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页获取系统参数配置
         * @param {string}[name]名称
         * @param {string}[code]编码
         * @param {string}[groupCode]常量所属分类的编码，来自于“常量的分类”字典
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function sysConfigPageGet(name?: string, code?: string, groupCode?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (groupCode !== undefined) {
                params['GroupCode'] = groupCode;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysConfig/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
