/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddDictDataInput,
   ChageStateDictDataInput,
   Condition,
   DeleteDictDataInput,
   UpdateDictDataInput,
   XnRestfulResultOfObject,
   } from '../models';

         /**
         * @summary增加字典值
         * @param {AddDictDataInput}[addDictDataInput]
         */
         export function sysDictDataAddPost(addDictDataInput?: AddDictDataInput, mode: ErrorMessageMode = 'message') {
            const params = {  addDictDataInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictData/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary修改字典值状态
         * @param {ChageStateDictDataInput}[chageStateDictDataInput]
         */
         export function sysDictDataChangeStatusPost(chageStateDictDataInput?: ChageStateDictDataInput, mode: ErrorMessageMode = 'message') {
            const params = {  chageStateDictDataInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictData/changeStatus',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除字典值
         * @param {DeleteDictDataInput}[deleteDictDataInput]
         */
         export function sysDictDataDeletePost(deleteDictDataInput?: DeleteDictDataInput, mode: ErrorMessageMode = 'message') {
            const params = {  deleteDictDataInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictData/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary字典值详情
         * @param {number}id主键Id
         */
         export function sysDictDataDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysDictDataDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictData/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新字典值
         * @param {UpdateDictDataInput}[updateDictDataInput]
         */
         export function sysDictDataEditPost(updateDictDataInput?: UpdateDictDataInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateDictDataInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictData/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取某个字典类型下字典值列表
         * @param {number}typeId字典类型Id
         */
         export function sysDictDataListGet(typeId: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'typeId' is not null or undefined
            assertParamExists('sysDictDataListGet', 'typeId', typeId)
            const params = {  } as any
            if (typeId !== undefined) {
                params['TypeId'] = typeId;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictData/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页查询字典值
         * @param {number}[typeId]字典类型Id
         * @param {string}[value]值
         * @param {string}[code]编码
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function sysDictDataPageGet(typeId?: number, value?: string, code?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (typeId !== undefined) {
                params['TypeId'] = typeId;
            }
            if (value !== undefined) {
                params['Value'] = value;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictData/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
