/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddDictTypeInput,
   ChangeStateDictTypeInput,
   Condition,
   DeleteDictTypeInput,
   UpdateDictTypeInput,
   XnRestfulResultOfListOfDictTreeOutput,
   XnRestfulResultOfObject,
   } from '../models';

         /**
         * @summary添加字典类型
         * @param {AddDictTypeInput}[addDictTypeInput]
         */
         export function sysDictTypeAddPost(addDictTypeInput?: AddDictTypeInput, mode: ErrorMessageMode = 'message') {
            const params = {  addDictTypeInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictType/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新字典类型状态
         * @param {ChangeStateDictTypeInput}[changeStateDictTypeInput]
         */
         export function sysDictTypeChangeStatusPost(changeStateDictTypeInput?: ChangeStateDictTypeInput, mode: ErrorMessageMode = 'message') {
            const params = {  changeStateDictTypeInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictType/changeStatus',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除字典类型
         * @param {DeleteDictTypeInput}[deleteDictTypeInput]
         */
         export function sysDictTypeDeletePost(deleteDictTypeInput?: DeleteDictTypeInput, mode: ErrorMessageMode = 'message') {
            const params = {  deleteDictTypeInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictType/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary字典类型详情
         * @param {number}id主键Id
         */
         export function sysDictTypeDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysDictTypeDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictType/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取字典类型下所有字典值
         * @param {string}code编码
         */
         export function sysDictTypeDropDownGet(code: string, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('sysDictTypeDropDownGet', 'code', code)
            const params = {  } as any
            if (code !== undefined) {
                params['Code'] = code;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictType/dropDown',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新字典类型
         * @param {UpdateDictTypeInput}[updateDictTypeInput]
         */
         export function sysDictTypeEditPost(updateDictTypeInput?: UpdateDictTypeInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateDictTypeInput  }
            return defHttp.request<void>(
              {
                url: '/sysDictType/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取字典类型列表
         */
         export function sysDictTypeListGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictType/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页查询字典类型
         * @param {string}[name]名称
         * @param {string}[code]编码
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function sysDictTypePageGet(name?: string, code?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysDictType/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary字典类型与字典值构造的字典树
         */
         export function sysDictTypeTreeGet(mode: ErrorMessageMode = 'message') {
            return defHttp.request<XnRestfulResultOfListOfDictTreeOutput>(
              {
                url: '/sysDictType/tree',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
              },
              {
                errorMessageMode: mode,
              })
         }
