/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddMenuInput,
   ChangeAppMenuInput,
   DeleteMenuInput,
   QueryMenuInput,
   UpdateMenuInput,
   XnRestfulResultOfListOfAntDesignTreeNode,
   XnRestfulResultOfObject,
   } from '../models';

         /**
         * @summary增加系统菜单
         * @param {AddMenuInput}[addMenuInput]
         */
         export function sysMenuAddPost(addMenuInput?: AddMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  addMenuInput  }
            return defHttp.request<void>(
              {
                url: '/sysMenu/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary根据系统应用切换菜单
         * @param {ChangeAppMenuInput}[changeAppMenuInput]
         */
         export function sysMenuChangePost(changeAppMenuInput?: ChangeAppMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  changeAppMenuInput  }
            return defHttp.request<XnRestfulResultOfListOfAntDesignTreeNode>(
              {
                url: '/sysMenu/change',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除系统菜单
         * @param {DeleteMenuInput}[deleteMenuInput]
         */
         export function sysMenuDeletePost(deleteMenuInput?: DeleteMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  deleteMenuInput  }
            return defHttp.request<void>(
              {
                url: '/sysMenu/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统菜单
         * @param {QueryMenuInput}[queryMenuInput]
         */
         export function sysMenuDetailPost(queryMenuInput?: QueryMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  queryMenuInput  }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysMenu/detail',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新系统菜单
         * @param {UpdateMenuInput}[updateMenuInput]
         */
         export function sysMenuEditPost(updateMenuInput?: UpdateMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateMenuInput  }
            return defHttp.request<void>(
              {
                url: '/sysMenu/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary系统菜单列表（树表）
         * @param {string}[name]名称
         * @param {string}[application]应用分类（应用编码）
         */
         export function sysMenuListGet(name?: string, application?: string, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (application !== undefined) {
                params['Application'] = application;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysMenu/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统菜单树，用于给角色授权时选择
         * @param {string}[application]应用分类（应用编码）
         */
         export function sysMenuTreeForGrantGet(application?: string, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (application !== undefined) {
                params['Application'] = application;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysMenu/treeForGrant',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取系统菜单树，用于新增、编辑时选择上级节点
         * @param {string}[application]应用分类（应用编码）
         */
         export function sysMenuTreeGet(application?: string, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (application !== undefined) {
                params['Application'] = application;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysMenu/tree',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
