/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { defHttp } from '/@/utils/http/axios';
import { RequestOptions, UploadFileParams } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddPosInput,
   DeletePosInput,
   PosInput,
   UpdatePosInput,
   XnRestfulResultOfObject,
   XnRestfulResultOfSysPos,
   } from '../models';

         /**
         * @summary 增加职位
         * @param {AddPosInput}[addPosInput]
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosAddPost(addPosInput?: AddPosInput, options?: RequestOptions) {
            const params = {  ...addPosInput  }
            return defHttp.request<void>(
              {
                url: '/sysPos/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              options
            )
         }

         /**
         * @summary 删除职位
         * @param {DeletePosInput}[deletePosInput]
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosDeletePost(deletePosInput?: DeletePosInput, options?: RequestOptions) {
            const params = {  ...deletePosInput  }
            return defHttp.request<void>(
              {
                url: '/sysPos/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              options
            )
         }

         /**
         * @summary 获取职位
         * @param {number}id 主键Id
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosDetailGet(id: number, options?: RequestOptions) {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysPosDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfSysPos>(
              {
                url: '/sysPos/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              options
            )
         }

         /**
         * @summary 更新职位
         * @param {UpdatePosInput}[updatePosInput]
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosEditPost(updatePosInput?: UpdatePosInput, options?: RequestOptions) {
            const params = {  ...updatePosInput  }
            return defHttp.request<void>(
              {
                url: '/sysPos/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              options
            )
         }

         /**
         * @summary 获取职位列表
         * @param {string}[name] 名称
         * @param {string}[code] 编码
         * @param {number}[sort] 排序
         * @param {string}[remark] 备注
         * @param {number}[status] 状态（字典 0正常 1停用 2删除）
         * @param {number}[pageNo] 当前页码
         * @param {number}[pageSize] 页码容量
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosListGet(name?: string, code?: string, sort?: number, remark?: string, status?: number, pageNo?: number, pageSize?: number, options?: RequestOptions) {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (sort !== undefined) {
                params['Sort'] = sort;
            }
            if (remark !== undefined) {
                params['Remark'] = remark;
            }
            if (status !== undefined) {
                params['Status'] = status;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysPos/list',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              options
            )
         }

         /**
         * @summary 分页获取职位
         * @param {PosInput}[posInput]
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosPage3Post(posInput?: PosInput, options?: RequestOptions) {
            const params = {  ...posInput  }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysPos/page@3',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              options
            )
         }

         /**
         * @summary 分页获取职位
         * @param {string}[name] 名称
         * @param {string}[code] 编码
         * @param {number}[sort] 排序
         * @param {string}[remark] 备注
         * @param {number}[status] 状态（字典 0正常 1停用 2删除）
         * @param {number}[pageNo] 当前页码
         * @param {number}[pageSize] 页码容量
         * @param {RequestOptions}options 额外配置，用来设置错误提示方法，是否返回原始数据，是否返回原始响应头，参数是否拼接到url等等
         */
         export function sysPosPageGet(name?: string, code?: string, sort?: number, remark?: string, status?: number, pageNo?: number, pageSize?: number, options?: RequestOptions) {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (code !== undefined) {
                params['Code'] = code;
            }
            if (sort !== undefined) {
                params['Sort'] = sort;
            }
            if (remark !== undefined) {
                params['Remark'] = remark;
            }
            if (status !== undefined) {
                params['Status'] = status;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysPos/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              options
            )
         }
