/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href=\'https://gitee.com/zuohuaijun/Admin.NET/\'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { defHttp } from '/@/utils/http/axios';
import { ErrorMessageMode } from '/@/utils/http/axios/types';
import { assertParamExists } from '../common';
import {
   AddTenantInput,
   Condition,
   DeleteTenantInput,
   GrantRoleMenuInput,
   QueryTenantInput,
   SysTenant,
   UpdateTenantInput,
   XnRestfulResultOfListOfInt64,
   XnRestfulResultOfObject,
   XnRestfulResultOfSysTenant,
   } from '../models';

         /**
         * @summary新增租户时，初始化数据
         * @param {SysTenant}[sysTenant]
         */
         export function apiTenantInitNewTenantPost(sysTenant?: SysTenant, mode: ErrorMessageMode = 'message') {
            const params = {  sysTenant  }
            return defHttp.request<void>(
              {
                url: '/api/tenant/init-new-tenant',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary增加租户
         * @param {AddTenantInput}[addTenantInput]
         */
         export function sysTenantAddPost(addTenantInput?: AddTenantInput, mode: ErrorMessageMode = 'message') {
            const params = {  addTenantInput  }
            return defHttp.request<void>(
              {
                url: '/sysTenant/add',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary删除租户
         * @param {DeleteTenantInput}[deleteTenantInput]
         */
         export function sysTenantDeletePost(deleteTenantInput?: DeleteTenantInput, mode: ErrorMessageMode = 'message') {
            const params = {  deleteTenantInput  }
            return defHttp.request<void>(
              {
                url: '/sysTenant/delete',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取租户
         * @param {number}id主键Id
         */
         export function sysTenantDetailGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysTenantDetailGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfSysTenant>(
              {
                url: '/sysTenant/detail',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary更新租户
         * @param {UpdateTenantInput}[updateTenantInput]
         */
         export function sysTenantEditPost(updateTenantInput?: UpdateTenantInput, mode: ErrorMessageMode = 'message') {
            const params = {  updateTenantInput  }
            return defHttp.request<void>(
              {
                url: '/sysTenant/edit',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary授权租户管理员角色菜单
         * @param {GrantRoleMenuInput}[grantRoleMenuInput]
         */
         export function sysTenantGrantMenuPost(grantRoleMenuInput?: GrantRoleMenuInput, mode: ErrorMessageMode = 'message') {
            const params = {  grantRoleMenuInput  }
            return defHttp.request<void>(
              {
                url: '/sysTenant/grantMenu',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary获取租户管理员角色拥有菜单Id集合
         * @param {number}id主键Id
         */
         export function sysTenantOwnMenuGet(id: number, mode: ErrorMessageMode = 'message') {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sysTenantOwnMenuGet', 'id', id)
            const params = {  } as any
            if (id !== undefined) {
                params['Id'] = id;
            }
            return defHttp.request<XnRestfulResultOfListOfInt64>(
              {
                url: '/sysTenant/ownMenu',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary分页查询租户
         * @param {string}[name]公司名称
         * @param {string}[host]主机
         * @param {string}[searchValue]搜索值
         * @param {number}[pageNo]当前页码
         * @param {number}[pageSize]页码容量
         * @param {string}[searchBeginTime]搜索开始时间
         * @param {string}[searchEndTime]搜索结束时间
         * @param {string}[sortField]排序字段
         * @param {string}[sortOrder]排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
         * @param {string}[descStr]降序排序(不要问我为什么是descend不是desc，前端约定参数就是这样)
         * @param {Array<Condition>}[searchParameters]复杂查询条件
         */
         export function sysTenantPageGet(name?: string, host?: string, searchValue?: string, pageNo?: number, pageSize?: number, searchBeginTime?: string, searchEndTime?: string, sortField?: string, sortOrder?: string, descStr?: string, searchParameters?: Array<Condition>, mode: ErrorMessageMode = 'message') {
            const params = {  } as any
            if (name !== undefined) {
                params['Name'] = name;
            }
            if (host !== undefined) {
                params['Host'] = host;
            }
            if (searchValue !== undefined) {
                params['SearchValue'] = searchValue;
            }
            if (pageNo !== undefined) {
                params['PageNo'] = pageNo;
            }
            if (pageSize !== undefined) {
                params['PageSize'] = pageSize;
            }
            if (searchBeginTime !== undefined) {
                params['SearchBeginTime'] = searchBeginTime;
            }
            if (searchEndTime !== undefined) {
                params['SearchEndTime'] = searchEndTime;
            }
            if (sortField !== undefined) {
                params['SortField'] = sortField;
            }
            if (sortOrder !== undefined) {
                params['SortOrder'] = sortOrder;
            }
            if (descStr !== undefined) {
                params['DescStr'] = descStr;
            }
            if (searchParameters) {
                params['SearchParameters'] = searchParameters;
            }
            return defHttp.request<XnRestfulResultOfObject>(
              {
                url: '/sysTenant/page',
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }

         /**
         * @summary重置租户管理员密码
         * @param {QueryTenantInput}[queryTenantInput]
         */
         export function sysTenantResetPwdPost(queryTenantInput?: QueryTenantInput, mode: ErrorMessageMode = 'message') {
            const params = {  queryTenantInput  }
            return defHttp.request<void>(
              {
                url: '/sysTenant/resetPwd',
                method: 'POST',
                headers: {'Content-Type': 'application/json-patch+json'},
                params
              },
              {
                errorMessageMode: mode,
              })
         }
